name: Build and Deploy to GH Pages

on:
  push:
    branch: master

jobs:
  build_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Test that this works
        run: echo "hello"
  another_job:
    name: Another job
    runs-on: ubuntu-latest
    steps:
      - name: Test that this works
        run: echo "hello again"
  a_third_job:
    name: A third job
    runs-on: ubuntu-latest
    needs: another_job
    steps:
      - name: Test that this works
        run: echo "hello again"

