name: Build and Deploy to GH Pages

on:
  push:
    branch: master

jobs:
  build_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Test that this works
        run: echo "hello"
